# Generated by Django 3.1.4 on 2020-12-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_email_subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
